<?php

namespace SiteBundle\Repository;

/**
 * AppareilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppareilRepository extends \Doctrine\ORM\EntityRepository
{
}
