<?php

namespace SiteBundle\Repository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllTag ()
    {
        $qb = $this->createQueryBuilder('a')
            ->where('a.tag = :tag');

        return $qb;
    }
}
