<?php

namespace AdminBundle\Repository;

/**
 * PhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllByTag ($tag)
    {
        $query = $this->createQueryBuilder('c')
            ->innerJoin('c.tags', 'tag')
            ->where('tag.label = :label')
            ->setParameter('label', $tag)
            ->getQuery();

        $products = $query->getResult();
        return $products;
    }
}
